### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [pronaypeddiraju/CSIRepository#1]
Instead of making an entire repo for CSI in yours. Make an organisation using the CSI email id and all members can be a part of it. And put all your projects there.

**Comment by pronaypeddiraju** [comment]
Okay taking note of this. Will take some time and do that or something on
those likes. Sounds like a legit idea. Don't know why I didn't think of
that

**Comment by ghost** [comment]
Cause you are still you. :-1:

**Comment by ghost** [comment]
You won't have trouble with master and branches that way. People can contribute to what they want.

**Comment by pronaypeddiraju** [comment]
Omg ! I'm sorry that I'm me man.
Maarega kya!

**Comment by pronaypeddiraju** [comment]
Cool cool. I will do that later then
